[package]
name = "probe-rs"
version = "0.5.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>", "Dominik Boehi <dominik.boehi@gmail.ch>"]
edition = "2018"
description = "A collection of on chip debugging tools to comminicate with ARM chips."
documentation = "https://docs.rs/probe-rs/"
homepage = "https://github.com/probe-rs/probe-rs"
repository = "https://github.com/probe-rs/probe-rs"
readme = "../README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[features]
default = ["builtin-targets"]

# Enable all built in targets.
builtin-targets = []

[dependencies]
log = "0.4.6"
num-traits = "0.2.8"
enum-primitive-derive = "0.1.2"
jep106 = "0.2.3"
scroll = "0.10.1"
rusb = "0.5.1"
lazy_static = "1.2.0"
hidapi = "1.1.0"
gimli = "0.20.0"
object = "0.17.0"
bitfield = "0.13.2"
derivative = "1.0.3"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_yaml = "0.8"
ihex = "1.1.2"
capstone = "0.6.0"
goblin = "0.2.0"
maplit = "1.0.2"
hexdump = "0.1.0"
dyn-clone = "1.0.1"
colored = "1.8.0"
thiserror = "1.0"

[build-dependencies]
probe-rs-t2rust  = { path = "../probe-rs-t2rust", version ="0.5.0" }

[dev-dependencies]
rand = "0.7.2"
structopt = "0.3"
pretty_env_logger = "0.4.0"
