version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/probe-rs"
    update_schedule: "daily"
  - package_manager: "rust:cargo"
    directory: "/cli"
    update_schedule: "daily"
  - package_manager: "rust:cargo"
    directory: "/gdb-server"
    update_schedule: "daily"
  - package_manager: "rust:cargo"
    directory: "/probe-rs-t2rust"
    update_schedule: "daily"
